handy_conclusions = {     "status": "done",
                          "score": "The score distribution reveals two distinct high-risk clusters, suggesting the presence of at least two different spam strategies: low-effort automated submissions and more sophisticated adaptive bots attempting to mimic human behavior.",
                   "fill_time": "The fill-time distribution is multimodal, indicating at least three distinct behavioral populations: automated submissions (<5s), fast interactions (5–10s), and normal user behavior (>30s). The presence of a stable peak  around 5–10 seconds suggests legitimate rapid users rather than misclassified bots.",
                   "activity":"The activity over time shows a highly irregular but continuous pattern of submissions, with no significant idle periods. Multiple recurring spikes (up to ~35 submissions per interval) suggest automated or semi-automated batch submissions rather than organic user behavior. The absence of clear daily or weekly human activity cycles indicates that a substantial portion of traffic is likely non-human. The pattern is consistent with distributed bot activity or scheduled spam campaigns operating at low but persistent intensity. Overall, the system is exposed to continuous background bot traffic with periodic bursts of higher intensity.",
                   "activity_one_day": "",
                            "activity_6_days": """The activity pattern shows a clear and consistent daily cycle, with significantly higher submission volume during daytime hours and reduced activity overnight.
The calculated hourly baseline successfully captures the expected traffic behavior across different times of day, making it possible to distinguish normal fluctuations from potentially unusual spikes.
Most detected anomalies occur during peak daytime activity, where submission counts temporarily exceed the normal expected range (mean ±2 standard deviations). These spikes may indicate:
short-term traffic bursts, automated activity, external referrals, or coordinated submission attempts.
The anomaly detection model appears effective for identifying statistically unusual behavior while still accounting for natural hourly traffic variation.
Because the baseline is calculated separately for each hour of the day, nighttime activity is not incorrectly compared against daytime peaks, resulting in more reliable anomaly detection.
The current analysis is based on a relatively short observation period (6 days), meaning the baseline may still evolve as additional historical data becomes available.
                            """,
                    "summary": "There are 1,400 IP addresses with a high probability of spam activity. Blocking these IPs would reduce traffic by 14%. <br>A single subnet accounts for 7.5% of all reports, which is an abnormally high concentration of traffic and suggests a common source of activity. Among the most active addresses, several consecutive IP addresses belonging to the same subnet and the same operator (185.220.101.*) appear. This concentration is unlikely for traffic originating from independent users and may indicate the use of a shared infrastructure for automated report generation."
}

